version: 2.1
jobs:
   build:
      machine:
          enabled: true
          image: ubuntu-2004:202107-02
      environment:
         DOCKER_BUILDKIT: 1
         COMPOSE_DOCKER_CLI_BUILD: 1
      steps:
         - checkout
         - run:
              name: docker build complete image
              command: build_type=package make build

         - run:
              name: docker build and --target test
              command: build_type=package make test

         - run:
              name: login to Dockerhub for release
              command: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin

         - run:
              name: push image version to Dockerhub
              command: build_type=package make release
